# Generated by Django 5.1.1 on 2024-09-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="market_bond_codes",
            new_name="market_bond_code",
        ),
    ]
