# Generated by Django 5.1.1 on 2024-09-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0002_rename_market_bond_codes_market_bond_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="market_bond_code",
            new_name="MarketBondCode",
        ),
    ]
