# Generated by Django 5.1.1 on 2024-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0003_rename_market_bond_code_marketbondcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketbondsearchinfo",
            name="tlg_rcvg_dtl_dtime",
            field=models.CharField(
                default=0, max_length=10, verbose_name="증권예탁결제원데이터"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marketbondsearchinfo",
            name="int_mned_dvsn_cd",
            field=models.CharField(
                choices=[("0", "null"), ("1", "일자기준"), ("2", "말일기준")],
                max_length=1,
                verbose_name="이자월말구분코드",
            ),
        ),
    ]
