# Generated by Django 5.1.1 on 2024-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0004_marketbondsearchinfo_tlg_rcvg_dtl_dtime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketbondsearchinfo",
            name="expd_dydv_calc_dcnt",
            field=models.CharField(max_length=9, verbose_name="만기일할계산일수"),
        ),
        migrations.AlterField(
            model_name="marketbondsearchinfo",
            name="int_mned_dvsn_cd",
            field=models.CharField(
                choices=[("0", "확인불가"), ("1", "일자기준"), ("2", "말일기준")],
                max_length=1,
                verbose_name="이자월말구분코드",
            ),
        ),
        migrations.AlterField(
            model_name="marketbondsearchinfo",
            name="ksd_indf_frqc_uder_calc_dcnt",
            field=models.CharField(
                max_length=5, verbose_name="증권예탁결제원이자지급주기미만"
            ),
        ),
        migrations.AlterField(
            model_name="marketbondsearchinfo",
            name="tlg_rcvg_dtl_dtime",
            field=models.CharField(max_length=10, verbose_name="전문수신상세일시"),
        ),
    ]
