# Generated by Django 5.1.1 on 2024-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0005_alter_marketbondsearchinfo_expd_dydv_calc_dcnt_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="marketbondinquiredailyitemchartprice",
            constraint=models.UniqueConstraint(
                fields=("stck_bsop_date",), name="uniuqe_daily_item_chart_price"
            ),
        ),
    ]
