# Generated by Django 5.1.1 on 2024-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "koreaib",
            "0006_marketbondinquiredailyitemchartprice_uniuqe_daily_item_chart_price",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="marketbondinquiredailyitemchartprice",
            name="uniuqe_daily_item_chart_price",
        ),
        migrations.AddConstraint(
            model_name="marketbondinquiredailyitemchartprice",
            constraint=models.UniqueConstraint(
                fields=("stck_bsop_date",), name="unique_daily_item_chart_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketbondinquiredailyprice",
            constraint=models.UniqueConstraint(
                fields=("stck_bsop_date",), name="unique_daily_price"
            ),
        ),
    ]
