# Generated by Django 5.1.1 on 2024-10-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "koreaib",
            "0007_remove_marketbondinquiredailyitemchartprice_uniuqe_daily_item_chart_price_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchkeyword",
            old_name="query",
            new_name="search_keyword",
        ),
        migrations.AddConstraint(
            model_name="navernews",
            constraint=models.UniqueConstraint(
                fields=("originallink",), name="unique_naver_news"
            ),
        ),
    ]
