# Generated by Django 5.1.1 on 2024-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0008_rename_query_searchkeyword_search_keyword_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="navernews",
            name="unique_naver_news",
        ),
        migrations.AlterField(
            model_name="navernews",
            name="originallink",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="원본 링크"
            ),
        ),
    ]
