# Generated by Django 5.1.1 on 2024-10-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0009_remove_navernews_unique_naver_news_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navernews",
            name="originallink",
            field=models.CharField(max_length=200, verbose_name="원본 링크"),
        ),
        migrations.AddConstraint(
            model_name="navernews",
            constraint=models.UniqueConstraint(
                fields=("originallink",), name="unique_naver_news"
            ),
        ),
    ]
