# Generated by Django 5.1.1 on 2024-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koreaib", "0010_alter_navernews_originallink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketbondinquireccnl",
            name="prdy_vrss_sign",
            field=models.CharField(max_length=1, verbose_name="전일 대비 부호"),
        ),
    ]
